# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/verilog_lab/SPI_PJT/AXI_SPI/AXI_SPI.srcs/sources_1/bd/AXI_SPI_block/ip/AXI_SPI_block_rst_ps7_0_50M_0/AXI_SPI_block_rst_ps7_0_50M_0.xci
# IP: The module: 'AXI_SPI_block_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/verilog_lab/SPI_PJT/AXI_SPI/AXI_SPI.gen/sources_1/bd/AXI_SPI_block/ip/AXI_SPI_block_rst_ps7_0_50M_0/AXI_SPI_block_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_SPI_block_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/verilog_lab/SPI_PJT/AXI_SPI/AXI_SPI.gen/sources_1/bd/AXI_SPI_block/ip/AXI_SPI_block_rst_ps7_0_50M_0/AXI_SPI_block_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_SPI_block_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/verilog_lab/SPI_PJT/AXI_SPI/AXI_SPI.gen/sources_1/bd/AXI_SPI_block/ip/AXI_SPI_block_rst_ps7_0_50M_0/AXI_SPI_block_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_SPI_block_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/verilog_lab/SPI_PJT/AXI_SPI/AXI_SPI.srcs/sources_1/bd/AXI_SPI_block/ip/AXI_SPI_block_rst_ps7_0_50M_0/AXI_SPI_block_rst_ps7_0_50M_0.xci
# IP: The module: 'AXI_SPI_block_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/verilog_lab/SPI_PJT/AXI_SPI/AXI_SPI.gen/sources_1/bd/AXI_SPI_block/ip/AXI_SPI_block_rst_ps7_0_50M_0/AXI_SPI_block_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_SPI_block_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/verilog_lab/SPI_PJT/AXI_SPI/AXI_SPI.gen/sources_1/bd/AXI_SPI_block/ip/AXI_SPI_block_rst_ps7_0_50M_0/AXI_SPI_block_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_SPI_block_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/verilog_lab/SPI_PJT/AXI_SPI/AXI_SPI.gen/sources_1/bd/AXI_SPI_block/ip/AXI_SPI_block_rst_ps7_0_50M_0/AXI_SPI_block_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_SPI_block_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
