# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/AXI_SPI.xdc

# Block Designs: bd/AXI_SPI_block/AXI_SPI_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_SPI_block || ORIG_REF_NAME==AXI_SPI_block} -quiet] -quiet

# IP: bd/AXI_SPI_block/ip/AXI_SPI_block_processing_system7_0_0/AXI_SPI_block_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_SPI_block_processing_system7_0_0 || ORIG_REF_NAME==AXI_SPI_block_processing_system7_0_0} -quiet] -quiet

# IP: bd/AXI_SPI_block/ip/AXI_SPI_block_AXI_SPI_0_0/AXI_SPI_block_AXI_SPI_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_SPI_block_AXI_SPI_0_0 || ORIG_REF_NAME==AXI_SPI_block_AXI_SPI_0_0} -quiet] -quiet

# IP: bd/AXI_SPI_block/ip/AXI_SPI_block_SPI_Master_0_0/AXI_SPI_block_SPI_Master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_SPI_block_SPI_Master_0_0 || ORIG_REF_NAME==AXI_SPI_block_SPI_Master_0_0} -quiet] -quiet

# IP: bd/AXI_SPI_block/ip/AXI_SPI_block_SPI_Slave_0_0/AXI_SPI_block_SPI_Slave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_SPI_block_SPI_Slave_0_0 || ORIG_REF_NAME==AXI_SPI_block_SPI_Slave_0_0} -quiet] -quiet

# IP: bd/AXI_SPI_block/ip/AXI_SPI_block_SPI_RAM_0_0/AXI_SPI_block_SPI_RAM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_SPI_block_SPI_RAM_0_0 || ORIG_REF_NAME==AXI_SPI_block_SPI_RAM_0_0} -quiet] -quiet

# IP: bd/AXI_SPI_block/ip/AXI_SPI_block_ps7_0_axi_periph_0/AXI_SPI_block_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_SPI_block_ps7_0_axi_periph_0 || ORIG_REF_NAME==AXI_SPI_block_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/AXI_SPI_block/ip/AXI_SPI_block_rst_ps7_0_50M_0/AXI_SPI_block_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_SPI_block_rst_ps7_0_50M_0 || ORIG_REF_NAME==AXI_SPI_block_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/AXI_SPI_block/ip/AXI_SPI_block_auto_pc_0/AXI_SPI_block_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_SPI_block_auto_pc_0 || ORIG_REF_NAME==AXI_SPI_block_auto_pc_0} -quiet] -quiet

# XDC: c:/verilog_lab/SPI_PJT/AXI_SPI/AXI_SPI.gen/sources_1/bd/AXI_SPI_block/AXI_SPI_block_ooc.xdc
