# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/verilog_lab/zynq_axi_uart_rxtx/zynq_axi_uart_rxtx_final/zynq_axi_uart_rxtx_final.srcs/sources_1/bd/axi_uart/ip/axi_uart_processing_system7_0_0/axi_uart_processing_system7_0_0.xci
# IP: The module: 'axi_uart_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/verilog_lab/zynq_axi_uart_rxtx/zynq_axi_uart_rxtx_final/zynq_axi_uart_rxtx_final.gen/sources_1/bd/axi_uart/ip/axi_uart_processing_system7_0_0/axi_uart_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_uart_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/verilog_lab/zynq_axi_uart_rxtx/zynq_axi_uart_rxtx_final/zynq_axi_uart_rxtx_final.srcs/sources_1/bd/axi_uart/ip/axi_uart_processing_system7_0_0/axi_uart_processing_system7_0_0.xci
# IP: The module: 'axi_uart_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/verilog_lab/zynq_axi_uart_rxtx/zynq_axi_uart_rxtx_final/zynq_axi_uart_rxtx_final.gen/sources_1/bd/axi_uart/ip/axi_uart_processing_system7_0_0/axi_uart_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_uart_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
