
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 7 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {AXI_SPI_block_i/AXI_SPI_0/inst/Write_Addr[0]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_Addr[1]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_Addr[2]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_Addr[3]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_Addr[4]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_Addr[5]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_Addr[6]}]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[0]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[1]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[2]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[3]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[4]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[5]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[6]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[7]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[8]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[9]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[10]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[11]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[12]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[13]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[14]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[15]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[16]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[17]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[18]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[19]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[20]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[21]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[22]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[23]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[24]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[25]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[26]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[27]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[28]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[29]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[30]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[31]}]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[0]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[1]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[2]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[3]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[4]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[5]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[6]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[7]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[8]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[9]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[10]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[11]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[12]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[13]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[14]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[15]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[16]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[17]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[18]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[19]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[20]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[21]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[22]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[23]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[24]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[25]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[26]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[27]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[28]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[29]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[30]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[31]}]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 2 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {AXI_SPI_block_i/AXI_SPI_0/inst/WR_CMD[0]} {AXI_SPI_block_i/AXI_SPI_0/inst/WR_CMD[1]}]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 32 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[0]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[1]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[2]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[3]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[4]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[5]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[6]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[7]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[8]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[9]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[10]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[11]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[12]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[13]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[14]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[15]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[16]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[17]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[18]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[19]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[20]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[21]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[22]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[23]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[24]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[25]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[26]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[27]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[28]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[29]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[30]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[31]}]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 8 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {AXI_SPI_block_i/AXI_SPI_0/inst/Write_data[0]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_data[1]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_data[2]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_data[3]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_data[4]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_data[5]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_data[6]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_data[7]}]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list AXI_SPI_block_i/AXI_SPI_0/inst/CSN]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list AXI_SPI_block_i/SPI_Slave_0/inst/MISO]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list AXI_SPI_block_i/SPI_Master_0/inst/MOSI]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list AXI_SPI_block_i/SPI_Slave_0/inst/RAM_WEN]]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list AXI_SPI_block_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 7 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {AXI_SPI_block_i/SPI_Slave_0/inst/RAM_Addr[0]} {AXI_SPI_block_i/SPI_Slave_0/inst/RAM_Addr[1]} {AXI_SPI_block_i/SPI_Slave_0/inst/RAM_Addr[2]} {AXI_SPI_block_i/SPI_Slave_0/inst/RAM_Addr[3]} {AXI_SPI_block_i/SPI_Slave_0/inst/RAM_Addr[4]} {AXI_SPI_block_i/SPI_Slave_0/inst/RAM_Addr[5]} {AXI_SPI_block_i/SPI_Slave_0/inst/RAM_Addr[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {AXI_SPI_block_i/SPI_Slave_0/inst/RAM_Wdata[0]} {AXI_SPI_block_i/SPI_Slave_0/inst/RAM_Wdata[1]} {AXI_SPI_block_i/SPI_Slave_0/inst/RAM_Wdata[2]} {AXI_SPI_block_i/SPI_Slave_0/inst/RAM_Wdata[3]} {AXI_SPI_block_i/SPI_Slave_0/inst/RAM_Wdata[4]} {AXI_SPI_block_i/SPI_Slave_0/inst/RAM_Wdata[5]} {AXI_SPI_block_i/SPI_Slave_0/inst/RAM_Wdata[6]} {AXI_SPI_block_i/SPI_Slave_0/inst/RAM_Wdata[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 3 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {AXI_SPI_block_i/SPI_Master_0/inst/next_state[0]} {AXI_SPI_block_i/SPI_Master_0/inst/next_state[1]} {AXI_SPI_block_i/SPI_Master_0/inst/next_state[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 3 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {AXI_SPI_block_i/SPI_Master_0/inst/curr_state[0]} {AXI_SPI_block_i/SPI_Master_0/inst/curr_state[1]} {AXI_SPI_block_i/SPI_Master_0/inst/curr_state[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {AXI_SPI_block_i/SPI_Master_0/inst/RD_Data[0]} {AXI_SPI_block_i/SPI_Master_0/inst/RD_Data[1]} {AXI_SPI_block_i/SPI_Master_0/inst/RD_Data[2]} {AXI_SPI_block_i/SPI_Master_0/inst/RD_Data[3]} {AXI_SPI_block_i/SPI_Master_0/inst/RD_Data[4]} {AXI_SPI_block_i/SPI_Master_0/inst/RD_Data[5]} {AXI_SPI_block_i/SPI_Master_0/inst/RD_Data[6]} {AXI_SPI_block_i/SPI_Master_0/inst/RD_Data[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 2 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {AXI_SPI_block_i/AXI_SPI_0/inst/WR_CMD[0]} {AXI_SPI_block_i/AXI_SPI_0/inst/WR_CMD[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 8 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {AXI_SPI_block_i/AXI_SPI_0/inst/Write_data[0]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_data[1]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_data[2]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_data[3]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_data[4]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_data[5]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_data[6]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_data[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 7 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {AXI_SPI_block_i/AXI_SPI_0/inst/Write_Addr[0]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_Addr[1]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_Addr[2]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_Addr[3]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_Addr[4]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_Addr[5]} {AXI_SPI_block_i/AXI_SPI_0/inst/Write_Addr[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[0]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[1]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[2]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[3]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[4]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[5]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[6]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[7]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[8]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[9]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[10]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[11]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[12]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[13]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[14]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[15]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[16]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[17]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[18]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[19]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[20]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[21]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[22]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[23]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[24]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[25]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[26]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[27]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[28]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[29]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[30]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg3[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[0]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[1]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[2]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[3]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[4]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[5]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[6]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[7]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[8]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[9]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[10]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[11]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[12]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[13]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[14]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[15]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[16]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[17]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[18]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[19]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[20]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[21]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[22]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[23]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[24]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[25]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[26]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[27]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[28]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[29]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[30]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg1[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 32 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[0]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[1]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[2]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[3]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[4]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[5]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[6]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[7]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[8]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[9]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[10]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[11]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[12]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[13]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[14]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[15]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[16]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[17]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[18]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[19]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[20]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[21]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[22]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[23]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[24]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[25]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[26]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[27]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[28]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[29]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[30]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg2[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 32 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[0]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[1]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[2]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[3]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[4]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[5]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[6]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[7]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[8]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[9]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[10]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[11]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[12]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[13]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[14]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[15]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[16]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[17]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[18]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[19]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[20]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[21]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[22]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[23]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[24]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[25]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[26]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[27]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[28]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[29]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[30]} {AXI_SPI_block_i/AXI_SPI_0/inst/slv_reg0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list AXI_SPI_block_i/AXI_SPI_0/inst/CSN]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list AXI_SPI_block_i/SPI_Slave_0/inst/MISO]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list AXI_SPI_block_i/SPI_Master_0/inst/MOSI]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list AXI_SPI_block_i/SPI_Slave_0/inst/RAM_WEN]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list AXI_SPI_block_i/SPI_Master_0/inst/SCLK]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
