set_property IOSTANDARD LVCMOS33 [get_ports {SW[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports BTN1]
set_property IOSTANDARD LVCMOS33 [get_ports BUSY]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports UART_TX]

set_property PACKAGE_PIN W19 [get_ports {SW[3]}]
set_property PACKAGE_PIN W18 [get_ports {SW[2]}]
set_property PACKAGE_PIN U19 [get_ports {SW[1]}]
set_property PACKAGE_PIN U18 [get_ports {SW[0]}]
set_property PACKAGE_PIN D19 [get_ports BTN1]
set_property PACKAGE_PIN L15 [get_ports BUSY]
set_property PACKAGE_PIN H16 [get_ports CLK]
set_property PACKAGE_PIN D20 [get_ports RST]
set_property PACKAGE_PIN W16 [get_ports UART_TX]

