set_property IOSTANDARD LVCMOS33 [get_ports {SW[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports BTN1]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports LED]
set_property IOSTANDARD LVCMOS33 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports TX]
set_property PACKAGE_PIN T10 [get_ports {SW[3]}]
set_property PACKAGE_PIN T11 [get_ports {SW[2]}]
set_property PACKAGE_PIN Y14 [get_ports {SW[1]}]
set_property PACKAGE_PIN W14 [get_ports {SW[0]}]
set_property PACKAGE_PIN H16 [get_ports CLK]
set_property PACKAGE_PIN D19 [get_ports BTN1]
set_property PACKAGE_PIN D20 [get_ports RST]
set_property PACKAGE_PIN L15 [get_ports LED]
set_property PACKAGE_PIN Y19 [get_ports TX]

set_property MARK_DEBUG true [get_nets TX_OBUF]
set_property MARK_DEBUG true [get_nets {SW_IBUF[0]}]
set_property MARK_DEBUG true [get_nets {SW_IBUF[1]}]
set_property MARK_DEBUG true [get_nets {SW_IBUF[2]}]
set_property MARK_DEBUG true [get_nets {SW_IBUF[3]}]
set_property MARK_DEBUG true [get_nets shift_done_reg_n_0]
set_property MARK_DEBUG true [get_nets send_done_reg_n_0]

set_property MARK_DEBUG true [get_nets {serial0_in[0]}]
set_property MARK_DEBUG true [get_nets {serial0_in[1]}]
set_property MARK_DEBUG true [get_nets {serial0_in[2]}]
set_property MARK_DEBUG true [get_nets {serial0_in[3]}]
set_property MARK_DEBUG true [get_nets {serial0_in[4]}]
set_property MARK_DEBUG true [get_nets {serial0_in[5]}]
set_property MARK_DEBUG true [get_nets {serial0_in[6]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list CLK_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {SW_IBUF[0]} {SW_IBUF[1]} {SW_IBUF[2]} {SW_IBUF[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 7 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {serial0_in[0]} {serial0_in[1]} {serial0_in[2]} {serial0_in[3]} {serial0_in[4]} {serial0_in[5]} {serial0_in[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list send_done_reg_n_0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list shift_done_reg_n_0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list TX_OBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets CLK_IBUF_BUFG]
