domain_path: C:\verilog_lab\zynq_axi_uart_rxtx_final_sw\axi_uart_rxtx_final\export\axi_uart_rxtx_final\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
