set_property SRC_FILE_INFO {cfile:C:/verilog_lab/zynq_axi_uart_rxtx_final/zynq_axi_uart_rxtx_final.srcs/constrs_1/new/debug.xdc rfile:../../../zynq_axi_uart_rxtx_final.srcs/constrs_1/new/debug.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T11 [get_ports rxd_0]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y14 [get_ports TX_0]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list axi_uart_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {axi_uart_i/my_uart_tx_0/inst/serial_0[0]} {axi_uart_i/my_uart_tx_0/inst/serial_0[1]} {axi_uart_i/my_uart_tx_0/inst/serial_0[2]} {axi_uart_i/my_uart_tx_0/inst/serial_0[3]} {axi_uart_i/my_uart_tx_0/inst/serial_0[4]} {axi_uart_i/my_uart_tx_0/inst/serial_0[5]} {axi_uart_i/my_uart_tx_0/inst/serial_0[6]} {axi_uart_i/my_uart_tx_0/inst/serial_0[7]} {axi_uart_i/my_uart_tx_0/inst/serial_0[8]}]]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {axi_uart_i/axi_slve_0/inst/slv_reg3[0]} {axi_uart_i/axi_slve_0/inst/slv_reg3[1]} {axi_uart_i/axi_slve_0/inst/slv_reg3[2]} {axi_uart_i/axi_slve_0/inst/slv_reg3[3]} {axi_uart_i/axi_slve_0/inst/slv_reg3[4]} {axi_uart_i/axi_slve_0/inst/slv_reg3[5]} {axi_uart_i/axi_slve_0/inst/slv_reg3[6]} {axi_uart_i/axi_slve_0/inst/slv_reg3[7]} {axi_uart_i/axi_slve_0/inst/slv_reg3[8]} {axi_uart_i/axi_slve_0/inst/slv_reg3[9]} {axi_uart_i/axi_slve_0/inst/slv_reg3[10]} {axi_uart_i/axi_slve_0/inst/slv_reg3[11]} {axi_uart_i/axi_slve_0/inst/slv_reg3[12]} {axi_uart_i/axi_slve_0/inst/slv_reg3[13]} {axi_uart_i/axi_slve_0/inst/slv_reg3[14]} {axi_uart_i/axi_slve_0/inst/slv_reg3[15]} {axi_uart_i/axi_slve_0/inst/slv_reg3[16]} {axi_uart_i/axi_slve_0/inst/slv_reg3[17]} {axi_uart_i/axi_slve_0/inst/slv_reg3[18]} {axi_uart_i/axi_slve_0/inst/slv_reg3[19]} {axi_uart_i/axi_slve_0/inst/slv_reg3[20]} {axi_uart_i/axi_slve_0/inst/slv_reg3[21]} {axi_uart_i/axi_slve_0/inst/slv_reg3[22]} {axi_uart_i/axi_slve_0/inst/slv_reg3[23]} {axi_uart_i/axi_slve_0/inst/slv_reg3[24]} {axi_uart_i/axi_slve_0/inst/slv_reg3[25]} {axi_uart_i/axi_slve_0/inst/slv_reg3[26]} {axi_uart_i/axi_slve_0/inst/slv_reg3[27]} {axi_uart_i/axi_slve_0/inst/slv_reg3[28]} {axi_uart_i/axi_slve_0/inst/slv_reg3[29]} {axi_uart_i/axi_slve_0/inst/slv_reg3[30]} {axi_uart_i/axi_slve_0/inst/slv_reg3[31]}]]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {axi_uart_i/axi_slve_0/inst/UART_TX_DATA[0]} {axi_uart_i/axi_slve_0/inst/UART_TX_DATA[1]} {axi_uart_i/axi_slve_0/inst/UART_TX_DATA[2]} {axi_uart_i/axi_slve_0/inst/UART_TX_DATA[3]} {axi_uart_i/axi_slve_0/inst/UART_TX_DATA[4]} {axi_uart_i/axi_slve_0/inst/UART_TX_DATA[5]} {axi_uart_i/axi_slve_0/inst/UART_TX_DATA[6]} {axi_uart_i/axi_slve_0/inst/UART_TX_DATA[7]}]]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {axi_uart_i/axi_slve_0/inst/slv_reg2[0]} {axi_uart_i/axi_slve_0/inst/slv_reg2[1]} {axi_uart_i/axi_slve_0/inst/slv_reg2[2]} {axi_uart_i/axi_slve_0/inst/slv_reg2[3]} {axi_uart_i/axi_slve_0/inst/slv_reg2[4]} {axi_uart_i/axi_slve_0/inst/slv_reg2[5]} {axi_uart_i/axi_slve_0/inst/slv_reg2[6]} {axi_uart_i/axi_slve_0/inst/slv_reg2[7]} {axi_uart_i/axi_slve_0/inst/slv_reg2[8]} {axi_uart_i/axi_slve_0/inst/slv_reg2[9]} {axi_uart_i/axi_slve_0/inst/slv_reg2[10]} {axi_uart_i/axi_slve_0/inst/slv_reg2[11]} {axi_uart_i/axi_slve_0/inst/slv_reg2[12]} {axi_uart_i/axi_slve_0/inst/slv_reg2[13]} {axi_uart_i/axi_slve_0/inst/slv_reg2[14]} {axi_uart_i/axi_slve_0/inst/slv_reg2[15]} {axi_uart_i/axi_slve_0/inst/slv_reg2[16]} {axi_uart_i/axi_slve_0/inst/slv_reg2[17]} {axi_uart_i/axi_slve_0/inst/slv_reg2[18]} {axi_uart_i/axi_slve_0/inst/slv_reg2[19]} {axi_uart_i/axi_slve_0/inst/slv_reg2[20]} {axi_uart_i/axi_slve_0/inst/slv_reg2[21]} {axi_uart_i/axi_slve_0/inst/slv_reg2[22]} {axi_uart_i/axi_slve_0/inst/slv_reg2[23]} {axi_uart_i/axi_slve_0/inst/slv_reg2[24]} {axi_uart_i/axi_slve_0/inst/slv_reg2[25]} {axi_uart_i/axi_slve_0/inst/slv_reg2[26]} {axi_uart_i/axi_slve_0/inst/slv_reg2[27]} {axi_uart_i/axi_slve_0/inst/slv_reg2[28]} {axi_uart_i/axi_slve_0/inst/slv_reg2[29]} {axi_uart_i/axi_slve_0/inst/slv_reg2[30]} {axi_uart_i/axi_slve_0/inst/slv_reg2[31]}]]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {axi_uart_i/axi_slve_0/inst/UART_RX_DATA[0]} {axi_uart_i/axi_slve_0/inst/UART_RX_DATA[1]} {axi_uart_i/axi_slve_0/inst/UART_RX_DATA[2]} {axi_uart_i/axi_slve_0/inst/UART_RX_DATA[3]} {axi_uart_i/axi_slve_0/inst/UART_RX_DATA[4]} {axi_uart_i/axi_slve_0/inst/UART_RX_DATA[5]} {axi_uart_i/axi_slve_0/inst/UART_RX_DATA[6]} {axi_uart_i/axi_slve_0/inst/UART_RX_DATA[7]}]]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {axi_uart_i/uart_rx_0/inst/AXI_RX_DATA[0]} {axi_uart_i/uart_rx_0/inst/AXI_RX_DATA[1]} {axi_uart_i/uart_rx_0/inst/AXI_RX_DATA[2]} {axi_uart_i/uart_rx_0/inst/AXI_RX_DATA[3]} {axi_uart_i/uart_rx_0/inst/AXI_RX_DATA[4]} {axi_uart_i/uart_rx_0/inst/AXI_RX_DATA[5]} {axi_uart_i/uart_rx_0/inst/AXI_RX_DATA[6]} {axi_uart_i/uart_rx_0/inst/AXI_RX_DATA[7]}]]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list axi_uart_i/uart_rx_0/inst/rx_done]]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list axi_uart_i/uart_rx_0/inst/RX_READY]]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list axi_uart_i/axi_slve_0/inst/UART_RX_READY]]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
