set_property MARK_DEBUG true [get_nets {curr_state_reg[0]}]
set_property MARK_DEBUG true [get_nets {curr_state_reg[1]}]
set_property MARK_DEBUG true [get_nets {cnt1[26]}]
set_property MARK_DEBUG true [get_nets {cnt1[0]}]
set_property MARK_DEBUG true [get_nets {cnt1[2]}]
set_property MARK_DEBUG true [get_nets {cnt1[3]}]
set_property MARK_DEBUG true [get_nets {cnt1[5]}]
set_property MARK_DEBUG true [get_nets {cnt1[6]}]
set_property MARK_DEBUG true [get_nets {cnt1[19]}]
set_property MARK_DEBUG true [get_nets {cnt1[1]}]
set_property MARK_DEBUG true [get_nets {cnt1[4]}]
set_property MARK_DEBUG true [get_nets {cnt1[11]}]
set_property MARK_DEBUG true [get_nets {cnt1[14]}]
set_property MARK_DEBUG true [get_nets {cnt1[15]}]
set_property MARK_DEBUG true [get_nets {cnt1[17]}]
set_property MARK_DEBUG true [get_nets {cnt1[18]}]
set_property MARK_DEBUG true [get_nets {cnt1[23]}]
set_property MARK_DEBUG true [get_nets {cnt1[7]}]
set_property MARK_DEBUG true [get_nets {cnt1[8]}]
set_property MARK_DEBUG true [get_nets {cnt1[10]}]
set_property MARK_DEBUG true [get_nets {cnt1[16]}]
set_property MARK_DEBUG true [get_nets {cnt1[21]}]
set_property MARK_DEBUG true [get_nets {cnt1[24]}]
set_property MARK_DEBUG true [get_nets {cnt1[25]}]
set_property MARK_DEBUG true [get_nets {cnt1[9]}]
set_property MARK_DEBUG true [get_nets {cnt1[12]}]
set_property MARK_DEBUG true [get_nets {cnt1[13]}]
set_property MARK_DEBUG true [get_nets {cnt1[20]}]
set_property MARK_DEBUG true [get_nets {cnt1[22]}]
set_property MARK_DEBUG true [get_nets ALARM_OBUF]
set_property MARK_DEBUG true [get_nets {start_sensing_reg[5]}]
set_property MARK_DEBUG true [get_nets {start_sensing_reg[7]}]
set_property MARK_DEBUG true [get_nets {start_sensing_reg[8]}]
set_property MARK_DEBUG true [get_nets {start_sensing_reg[0]}]
set_property MARK_DEBUG true [get_nets {start_sensing_reg[1]}]
set_property MARK_DEBUG true [get_nets {start_sensing_reg[2]}]
set_property MARK_DEBUG true [get_nets {start_sensing_reg[3]}]
set_property MARK_DEBUG true [get_nets {start_sensing_reg[4]}]
set_property MARK_DEBUG true [get_nets {start_sensing_reg[6]}]
set_property MARK_DEBUG true [get_nets {start_sensing_reg[9]}]
set_property MARK_DEBUG true [get_nets SENSOR_IBUF]
connect_debug_port u_ila_0/probe1 [get_nets [list {start_sensing_reg[0]} {start_sensing_reg[1]} {start_sensing_reg[2]} {start_sensing_reg[3]} {start_sensing_reg[4]} {start_sensing_reg[5]} {start_sensing_reg[6]} {start_sensing_reg[7]} {start_sensing_reg[8]} {start_sensing_reg[9]}]]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list CLK_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 10 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {start_sensing[0]} {start_sensing[1]} {start_sensing[2]} {start_sensing[3]} {start_sensing[4]} {start_sensing[5]} {start_sensing[6]} {start_sensing[7]} {start_sensing[8]} {start_sensing[9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {curr_state_reg[0]} {curr_state_reg[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 27 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {cnt1[0]} {cnt1[1]} {cnt1[2]} {cnt1[3]} {cnt1[4]} {cnt1[5]} {cnt1[6]} {cnt1[7]} {cnt1[8]} {cnt1[9]} {cnt1[10]} {cnt1[11]} {cnt1[12]} {cnt1[13]} {cnt1[14]} {cnt1[15]} {cnt1[16]} {cnt1[17]} {cnt1[18]} {cnt1[19]} {cnt1[20]} {cnt1[21]} {cnt1[22]} {cnt1[23]} {cnt1[24]} {cnt1[25]} {cnt1[26]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list ALARM_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list SENSOR_IBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets CLK_IBUF_BUFG]
