set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports RST]
set_property PACKAGE_PIN D20 [get_ports RST]
set_property PACKAGE_PIN D19 [get_ports CLK]
set_property PACKAGE_PIN Y18 [get_ports {Q[0]}]
set_property PACKAGE_PIN Y19 [get_ports {Q[1]}]
set_property PACKAGE_PIN Y16 [get_ports {Q[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q[0]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CLK_IBUF]