# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/verilog_lab/Zynq_basic_system/Zynq_basic_system.srcs/sources_1/bd/zynq_basys/ip/zynq_basys_rst_ps7_0_50M_0/zynq_basys_rst_ps7_0_50M_0.xci
# IP: The module: 'zynq_basys_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/verilog_lab/Zynq_basic_system/Zynq_basic_system.gen/sources_1/bd/zynq_basys/ip/zynq_basys_rst_ps7_0_50M_0/zynq_basys_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_basys_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/verilog_lab/Zynq_basic_system/Zynq_basic_system.gen/sources_1/bd/zynq_basys/ip/zynq_basys_rst_ps7_0_50M_0/zynq_basys_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_basys_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/verilog_lab/Zynq_basic_system/Zynq_basic_system.gen/sources_1/bd/zynq_basys/ip/zynq_basys_rst_ps7_0_50M_0/zynq_basys_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_basys_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/verilog_lab/Zynq_basic_system/Zynq_basic_system.srcs/sources_1/bd/zynq_basys/ip/zynq_basys_rst_ps7_0_50M_0/zynq_basys_rst_ps7_0_50M_0.xci
# IP: The module: 'zynq_basys_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/verilog_lab/Zynq_basic_system/Zynq_basic_system.gen/sources_1/bd/zynq_basys/ip/zynq_basys_rst_ps7_0_50M_0/zynq_basys_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_basys_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/verilog_lab/Zynq_basic_system/Zynq_basic_system.gen/sources_1/bd/zynq_basys/ip/zynq_basys_rst_ps7_0_50M_0/zynq_basys_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_basys_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/verilog_lab/Zynq_basic_system/Zynq_basic_system.gen/sources_1/bd/zynq_basys/ip/zynq_basys_rst_ps7_0_50M_0/zynq_basys_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_basys_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
