# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/debug.xdc

# Block Designs: bd/axi_uart/axi_uart.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_uart || ORIG_REF_NAME==axi_uart} -quiet] -quiet

# IP: bd/axi_uart/ip/axi_uart_processing_system7_0_0/axi_uart_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_uart_processing_system7_0_0 || ORIG_REF_NAME==axi_uart_processing_system7_0_0} -quiet] -quiet

# IP: bd/axi_uart/ip/axi_uart_axi_slve_0_0/axi_uart_axi_slve_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_uart_axi_slve_0_0 || ORIG_REF_NAME==axi_uart_axi_slve_0_0} -quiet] -quiet

# IP: bd/axi_uart/ip/axi_uart_my_uart_tx_0_0/axi_uart_my_uart_tx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_uart_my_uart_tx_0_0 || ORIG_REF_NAME==axi_uart_my_uart_tx_0_0} -quiet] -quiet

# IP: bd/axi_uart/ip/axi_uart_uart_rx_0_0/axi_uart_uart_rx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_uart_uart_rx_0_0 || ORIG_REF_NAME==axi_uart_uart_rx_0_0} -quiet] -quiet

# IP: bd/axi_uart/ip/axi_uart_ps7_0_axi_periph_0/axi_uart_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_uart_ps7_0_axi_periph_0 || ORIG_REF_NAME==axi_uart_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/axi_uart/ip/axi_uart_rst_ps7_0_100M_0/axi_uart_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_uart_rst_ps7_0_100M_0 || ORIG_REF_NAME==axi_uart_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/axi_uart/ip/axi_uart_system_ila_0_0/axi_uart_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_uart_system_ila_0_0 || ORIG_REF_NAME==axi_uart_system_ila_0_0} -quiet] -quiet

# IP: bd/axi_uart/ip/axi_uart_auto_pc_0/axi_uart_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_uart_auto_pc_0 || ORIG_REF_NAME==axi_uart_auto_pc_0} -quiet] -quiet

# XDC: c:/verilog_lab/zynq_axi_uart_rxtx_final/zynq_axi_uart_rxtx_final.gen/sources_1/bd/axi_uart/axi_uart_ooc.xdc
