# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/verilog_lab/axi4_lite/axi4_lite.srcs/sources_1/bd/myip_v1_0_bfm_1/ip/myip_v1_0_bfm_1_master_0_0/myip_v1_0_bfm_1_master_0_0.xci
# IP: The module: 'myip_v1_0_bfm_1_master_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/verilog_lab/axi4_lite/axi4_lite.gen/sources_1/bd/myip_v1_0_bfm_1/ip/myip_v1_0_bfm_1_master_0_0/myip_v1_0_bfm_1_master_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myip_v1_0_bfm_1_master_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/verilog_lab/axi4_lite/axi4_lite.srcs/sources_1/bd/myip_v1_0_bfm_1/ip/myip_v1_0_bfm_1_master_0_0/myip_v1_0_bfm_1_master_0_0.xci
# IP: The module: 'myip_v1_0_bfm_1_master_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/verilog_lab/axi4_lite/axi4_lite.gen/sources_1/bd/myip_v1_0_bfm_1/ip/myip_v1_0_bfm_1_master_0_0/myip_v1_0_bfm_1_master_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myip_v1_0_bfm_1_master_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
