domain_path: C:\verilog_lab\Zynq_axi_7segment_SW\Zynq_axi_7segment\export\Zynq_axi_7segment\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
